service: portfolio

image: sandy851/portfolio

registry: 
  username: sandy851
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

servers:
  web:
    - 157.245.38.99

proxy:
  host: 157.245.38.99

env:
  clear:
    RAILS_ENV: production

  secret:
    - SECRET_KEY_BASE

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "portfolio_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  local: true
  arch: amd64

ssh:
  user: deploy
  keys:
    - ~/.ssh/portfolio_deploy
